export const SHOW_TENANT_DIALOG = 'SHOW_TENANT_DIALOG';
export const HIDE_TENANT_DIALOG = 'HIDE_TENANT_DIALOG';
export const LOAD_TENANTS = 'LOAD_TENANTS';
export const TENANTS_LOADED = 'TENANTS_LOADED';