export const LOAD_TENANTS = '@@TENANT/LOAD_TENANTS';
export const TENANTS_LOADED = '@@TENANT/TENANTS_LOADED';
export const SHOW_TENANT_DIALOG = '@@TENANT/SHOW_DIALOG'
export const HIDE_TENANT_DIALOG = '@@TENANT/HIDE_DIALOG'