export const LOADING = '@@SHARED/LOADING';
export const USERINFORMATION_UPDATING = '@@SHARED/USERINFORMATION_UPDATEING';
export const USERINFORMATION_UPDATED = '@@SHARED/USERINFORMATION_UPDATED';
export const CURRENT_USER = '@@SHARED/CURRENT_USER';
export const LOGIN = '@@SHARED/LOGIN_SUCCESS'
export const LOGIN_FAILURE = '@@SHARED/LOGIN_FAILURE'
export const LOGOUT = '@@SHARED/LOGOUT'
export const USERINFORMATION_FETCHED = '@@SHARED/USERINFORMATION_FETCHED'