export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHED_DATA = "FETCHED_DATA";
export const APPOINTMENT_ADD = "APPOINTMENT_ADD";
export const APPOINTMENT_ADDED = "APPOINTMENT_ADDED";
export const APPOINTMENT_JOIN = "APPOINTMENT_JOIN";
export const APPOINTMENT_JOINED = "APPOINTMENT_JOINED";