export const FETCHING_DATA = "@@APPOINTMENT/FETCHING_DATA";
export const FETCHED_DATA = "@@APPOINTMENT/FETCHED_DATA";
export const APPOINTMENT_ADD = "@@APPOINTMENT/APPOINTMENT_ADD";
export const APPOINTMENT_ADDED = "@@APPOINTMENT/APPOINTMENT_ADDED";
export const APPOINTMENT_JOIN = "@@APPOINTMENT/APPOINTMENT_JOIN";
export const APPOINTMENT_JOINED = "@@APPOINTMENT/APPOINTMENT_JOINED";
export const APPOINTMENT_DELETED = "@@APPOINTMENT/APPOINTMENT_DELETED"
export const JOIN_APPOINTMENT = "@@APPOINTMENT/JOIN_APPOINTMENT";